on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main
    paths:
      - 'major/**'

jobs:
  dummy_test:
    runs-on: ubuntu-latest
    steps:
       - run: echo 'Make renovate automerge excuted'
       
       
       
